"""预置 Python 编程知识图谱"""

PYTHON_KNOWLEDGE_GRAPH = {
    "title": "Python 编程入门到进阶",
    "description": "系统学习 Python 编程，从基础语法到面向对象",
    "domain": "python",
    "estimated_hours": 40,
    "nodes": [
        {
            "id": "n1",
            "name": "变量与数据类型",
            "description": "Python 基本数据类型：int, float, str, bool，变量赋值与类型转换",
            "difficulty": 1,
            "estimated_minutes": 60,
            "prerequisites": [],
            "learning_objectives": ["理解变量概念", "掌握基本数据类型", "学会类型转换"],
            "resource_types": ["note", "exercise", "code_example"],
        },
        {
            "id": "n2",
            "name": "运算符与表达式",
            "description": "算术、比较、逻辑、赋值运算符，表达式求值顺序",
            "difficulty": 1,
            "estimated_minutes": 45,
            "prerequisites": ["n1"],
            "learning_objectives": ["掌握各类运算符", "理解优先级", "编写复合表达式"],
            "resource_types": ["note", "exercise"],
        },
        {
            "id": "n3",
            "name": "条件语句",
            "description": "if/elif/else 分支结构，条件表达式，嵌套条件",
            "difficulty": 2,
            "estimated_minutes": 60,
            "prerequisites": ["n2"],
            "learning_objectives": ["掌握条件判断", "理解分支逻辑", "避免常见陷阱"],
            "resource_types": ["note", "exercise", "code_example"],
        },
        {
            "id": "n4",
            "name": "循环结构",
            "description": "for 循环、while 循环、break/continue、循环嵌套",
            "difficulty": 2,
            "estimated_minutes": 90,
            "prerequisites": ["n3"],
            "learning_objectives": ["掌握 for/while", "理解循环控制", "解决迭代问题"],
            "resource_types": ["note", "exercise", "code_example"],
        },
        {
            "id": "n5",
            "name": "函数定义",
            "description": "函数定义与调用、参数类型、返回值、作用域、lambda",
            "difficulty": 3,
            "estimated_minutes": 120,
            "prerequisites": ["n4"],
            "learning_objectives": ["定义和调用函数", "理解参数传递", "掌握作用域规则"],
            "resource_types": ["note", "exercise", "code_example"],
        },
        {
            "id": "n6",
            "name": "列表与元组",
            "description": "列表创建、索引、切片、方法；元组不可变性；列表推导式",
            "difficulty": 2,
            "estimated_minutes": 90,
            "prerequisites": ["n4"],
            "learning_objectives": ["掌握列表操作", "理解可变与不可变", "使用列表推导式"],
            "resource_types": ["note", "exercise", "code_example"],
        },
        {
            "id": "n7",
            "name": "字典与集合",
            "description": "字典创建与操作、集合运算、哈希与可哈希类型",
            "difficulty": 2,
            "estimated_minutes": 75,
            "prerequisites": ["n6"],
            "learning_objectives": ["掌握字典操作", "理解哈希原理", "使用集合运算"],
            "resource_types": ["note", "exercise", "code_example"],
        },
        {
            "id": "n8",
            "name": "字符串处理",
            "description": "字符串方法、格式化（f-string）、正则表达式基础",
            "difficulty": 2,
            "estimated_minutes": 60,
            "prerequisites": ["n6"],
            "learning_objectives": ["掌握字符串方法", "使用 f-string", "基础正则匹配"],
            "resource_types": ["note", "exercise", "code_example"],
        },
        {
            "id": "n9",
            "name": "文件操作",
            "description": "文件读写、上下文管理器（with）、CSV/JSON 处理",
            "difficulty": 3,
            "estimated_minutes": 75,
            "prerequisites": ["n7", "n8"],
            "learning_objectives": ["读写文本文件", "使用 with 语句", "处理结构化数据"],
            "resource_types": ["note", "exercise", "code_example"],
        },
        {
            "id": "n10",
            "name": "异常处理",
            "description": "try/except/finally、自定义异常、异常链",
            "difficulty": 3,
            "estimated_minutes": 60,
            "prerequisites": ["n5"],
            "learning_objectives": ["捕获和处理异常", "自定义异常类", "编写健壮代码"],
            "resource_types": ["note", "exercise", "code_example"],
        },
        {
            "id": "n11",
            "name": "面向对象基础",
            "description": "类与对象、属性与方法、继承、多态、魔术方法",
            "difficulty": 4,
            "estimated_minutes": 150,
            "prerequisites": ["n5", "n10"],
            "learning_objectives": ["定义类和对象", "理解继承多态", "使用魔术方法"],
            "resource_types": ["note", "exercise", "code_example"],
        },
        {
            "id": "n12",
            "name": "模块与包",
            "description": "import 机制、标准库常用模块、pip 包管理、虚拟环境",
            "difficulty": 3,
            "estimated_minutes": 60,
            "prerequisites": ["n11"],
            "learning_objectives": ["理解模块系统", "使用标准库", "管理第三方包"],
            "resource_types": ["note", "exercise", "code_example"],
        },
    ],
    "edges": [
        {"source": "n1", "target": "n2", "relation": "prerequisite"},
        {"source": "n2", "target": "n3", "relation": "prerequisite"},
        {"source": "n3", "target": "n4", "relation": "prerequisite"},
        {"source": "n4", "target": "n5", "relation": "prerequisite"},
        {"source": "n4", "target": "n6", "relation": "prerequisite"},
        {"source": "n6", "target": "n7", "relation": "prerequisite"},
        {"source": "n6", "target": "n8", "relation": "prerequisite"},
        {"source": "n7", "target": "n9", "relation": "prerequisite"},
        {"source": "n8", "target": "n9", "relation": "prerequisite"},
        {"source": "n5", "target": "n10", "relation": "prerequisite"},
        {"source": "n5", "target": "n11", "relation": "prerequisite"},
        {"source": "n10", "target": "n11", "relation": "prerequisite"},
        {"source": "n11", "target": "n12", "relation": "prerequisite"},
    ],
}
